insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (1, 'Orville', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'wbloggett0@xrea.com', 'Wandie', 'Dransfield', TO_DATE('2016-11-07', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (2, 'Dougie', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'mbleaden1@e-recht24.de', 'Marian', 'Quartly', TO_DATE('2016-05-17', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (3, 'Kelsey', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'dverlinden2@aboutads.info', 'Dallas', 'Burkin', TO_DATE('2016-11-08', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (4, 'Adey', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'bkitchiner3@redcross.org', 'Bird', 'Canning', TO_DATE('2016-07-14', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (5, 'Bianca', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'jbrands4@twitpic.com', 'Jesus', 'Kesteven', TO_DATE('2017-01-16', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (6, 'Bertha', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'jrumbold5@engadget.com', 'Joelly', 'Ovitz', TO_DATE('2017-03-27', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (7, 'Lisha', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'mvan der kruys6@ifeng.com', 'Marmaduke', 'Ollenbuttel', TO_DATE('2016-07-30', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (8, 'Gale', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'eskeels7@google.co.uk', 'Ellyn', 'Southby', TO_DATE('2017-04-13', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (9, 'Malina', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'fyurivtsev8@mapquest.com', 'Franzen', 'Wickwar', TO_DATE('2016-05-23', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (10, 'Maritsa', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'mfeatherbie9@nasa.gov', 'Madlin', 'Wathen', TO_DATE('2016-06-04', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (11, 'Roberta', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'svasyatkina@ucsd.edu', 'Suellen', 'Chominski', TO_DATE('2016-12-06', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (12, 'Wanda', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'sorsayb@sohu.com', 'Sig', 'Jillard', TO_DATE('2016-12-03', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (13, 'Kalie', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'abraidc@ycombinator.com', 'Ally', 'Wilshire', TO_DATE('2016-09-18', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (14, 'Denny', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'dspeechlyd@rakuten.co.jp', 'Dyana', 'Letford', TO_DATE('2016-11-26', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (15, 'Rockie', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'gbovairde@hud.gov', 'Gay', 'Zorzin', TO_DATE('2016-08-05', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (16, 'Vivyanne', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'tgiordanof@artisteer.com', 'Tally', 'Rosenstiel', TO_DATE('2017-01-27', 'yyyy-mm-dd'), 0);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (17, 'Juliet', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'krobetg@google.it', 'Kingsly', 'Skelhorn', TO_DATE('2016-11-01', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (18, 'Hastings', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'mdoudnyh@dmoz.org', 'Modesta', 'Krelle', TO_DATE('2016-08-27', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (19, 'Fina', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'lbastonei@dropbox.com', 'Lyndsay', 'Bleby', TO_DATE('2016-05-01', 'yyyy-mm-dd'), 1);
insert into USERS (US_ID_PK, US_LOGIN, US_PASSWORD, US_EMAIL, US_NAME, US_SURNAME, US_CREATION_DATE, US_ROLE) values (20, 'Clyde', '$2a$10$8jTNJqwX/jaJehssYn8HUO5uOhayAuVDTR5ZQrKu3EY5HYrgX1Z3W', 'avaudj@4shared.com', 'Auroora', 'Scrinage', TO_DATE('2017-03-04', 'yyyy-mm-dd'), 0);

insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (1, 'China');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (2, 'Belarus');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (3, 'India');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (4, 'Ukraine');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (5, 'Indonesia');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (6, 'Japan');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (7, 'Egypt');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (8, 'Mexico');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (9, 'Peru');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (10, 'South Africa');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (11, 'South Korea');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (12, 'Germany');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (13, 'Kenya');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (14, 'Singapore');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (15, 'Saudi Arabia');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (16, 'United States');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (17, 'North Korea');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (18, 'Russia');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (19, 'Brazil');
insert into COUNTRIES (CN_ID_PK, CN_TITLE) values (20, 'Colombia');

insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (1, 'Jianchang', 1);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (2, 'Minsk', 2);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (3, 'Gangmei', 3);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (4, 'Bratslav', 4);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (5, 'Jakarta', 5);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (6, 'Yokohama', 6);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (7, 'Alexandria', 7);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (8, 'Mexico City', 8);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (9, 'Lima', 9);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (10, 'Cape Town', 10);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (11, 'Seoul', 11);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (12, 'Berlin', 12);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (13, 'Nairobi', 13);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (14, 'Singapore', 14);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (15, 'Jeddah', 15);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (16, 'New York City', 16);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (17, 'Pyongyang', 17);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (18, 'Moscow', 18);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (19, 'Rio de Janeiro', 19);
insert into CITIES (CT_ID_PK, CT_TITLE, CT_COUNTRY_ID) values (20, 'Bogota', 20);

insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (1, 1, 'Y-find', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'ENTIRE_HOUSE', 58.1108, 3, 7, 'BOOKED', '3939 Monterey Place', 1);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (2, 2, 'Tin', 'Morbi a ipsum.', 'FLAT', 39.7789, 7, 1, 'AVAILABLE', '11816 Jana Way', 2);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (3, 3, 'Hatity', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'ROOM', 64.4239, 2, 7, 'AVAILABLE', '29108 Milwaukee Lane', 3);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (4, 4, 'Alphazap', 'Nam nulla.', 'ROOM', 88.1665, 5, 6, 'BOOKED', '509 Vera Terrace', 4);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (5, 5, 'Cookley', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'ENTIRE_HOUSE', 80.0737, 2, 2, 'BOOKED', '7515 Darwin Center', 5);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (6, 6, 'Bitchip', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'ENTIRE_HOUSE', 47.3803, 7, 4, 'AVAILABLE', '99096 Roxbury Circle', 6);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (7, 7, 'Zontrax', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'ENTIRE_HOUSE', 39.2305, 5, 2, 'AVAILABLE', '8 Erie Alley', 7);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (8, 8, 'Flowdesk', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'ROOM', 97.0541, 3, 2, 'AVAILABLE', '486 Hazelcrest Trail', 8);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (9, 9, 'Zamit', 'In hac habitasse platea dictumst.', 'ROOM', 48.4441, 5, 1, 'BOOKED', '4385 Lawn Way', 9);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (10, 10, 'Zontrax', 'Vivamus tortor. Duis mattis egestas metus.', 'ENTIRE_HOUSE', 59.7057, 1, 2, 'AVAILABLE', '8366 Sunbrook Parkway', 10);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (11, 11, 'Flexidy', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'FLAT', 63.4972, 2, 5, 'AVAILABLE', '38 Basil Court', 11);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (12, 12, 'Cardify', 'Nulla facilisi.', 'ENTIRE_HOUSE', 52.7909, 6, 1, 'BOOKED', '9 Maryland Way', 12);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (13, 13, 'Temp', 'Proin eu mi. Nulla ac enim.', 'ROOM', 16.5226, 3, 2, 'AVAILABLE', '90 Village Green Lane', 13);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (14, 14, 'Flexidy', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'ROOM', 44.5396, 3, 2, 'BOOKED', '48342 Vahlen Way', 14);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (15, 15, 'Andalax', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'ENTIRE_HOUSE', 29.6798, 1, 4, 'AVAILABLE', '07 Holmberg Avenue', 15);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (16, 16, 'Toughjoyfax', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'ROOM', 88.0265, 3, 5, 'BOOKED', '4 Gerald Court', 16);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (17, 17, 'Voltsillam', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 'FLAT', 33.955, 6, 6, 'BOOKED', '03548 Brown Junction', 17);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (18, 18, 'Otcom', 'Morbi porttitor lorem id ligula.', 'ENTIRE_HOUSE', 86.0802, 3, 2, 'AVAILABLE', '989 Bultman Alley', 18);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (19, 19, 'Duobam', 'Vivamus tortor. Duis mattis egestas metus.', 'ROOM', 9.2619, 4, 2, 'AVAILABLE', '5744 Morningstar Trail', 19);
insert into APARTMENTS (AP_ID_PK, AP_OWNER_ID, AP_TITLE, AP_DESCRIPTION, AP_TYPE, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_BED_NUMBER, AP_STATUS, AP_ADDRESS, AP_CITY_ID) values (20, 20, 'Mat Lam Tam', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'ROOM', 89.8284, 3, 6, 'AVAILABLE', '32340 Stoughton Center', 20);
