-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2017-04-05 16:56:46 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE APARTMENTS
  (
    ap_id_pk            INTEGER NOT NULL ,
    ap_owner_id         INTEGER NOT NULL ,
    ap_title            VARCHAR2 (255 CHAR) NOT NULL ,
    ap_description      VARCHAR2 (1000 CHAR) ,
    ap_type             VARCHAR2 (100 CHAR) NOT NULL ,
    ap_price            NUMBER (10, 4) NOT NULL ,
    ap_max_guest_number INTEGER NOT NULL ,
    ap_bed_number       SMALLINT NOT NULL ,
    ap_status           VARCHAR2 (100 CHAR) NOT NULL ,
    ap_address          VARCHAR2 (300 CHAR) NOT NULL ,
    ap_city_id          INTEGER NOT NULL
  ) ;
ALTER TABLE APARTMENTS ADD CONSTRAINT APARTMENTS_PK PRIMARY KEY ( ap_id_pk ) ;
/

CREATE TABLE CITIES
  (
    ct_id_pk      INTEGER NOT NULL ,
    ct_title      VARCHAR2 (255 CHAR) NOT NULL ,
    ct_country_id INTEGER NOT NULL
  ) ;
ALTER TABLE CITIES ADD CONSTRAINT CITIES_PK PRIMARY KEY ( ct_id_pk ) ;
/

CREATE TABLE COUNTRIES
  (
    cn_id_pk INTEGER NOT NULL ,
    cn_title VARCHAR2 (255 CHAR) NOT NULL
  ) ;
ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRIES_PK PRIMARY KEY ( cn_id_pk ) ;
ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRIES__UN UNIQUE ( cn_title ) ;
/

CREATE TABLE USERS
  (
    us_id_pk         INTEGER NOT NULL ,
    us_login         VARCHAR2 (255 CHAR) NOT NULL ,
    us_password      VARCHAR2 (60 CHAR) NOT NULL ,
    us_email         VARCHAR2 (255 CHAR) NOT NULL ,
    us_name          VARCHAR2 (255 CHAR) NOT NULL ,
    us_surname       VARCHAR2 (255 CHAR) NOT NULL ,
    us_creation_date DATE NOT NULL ,
    us_role          SMALLINT NOT NULL
  ) ;
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY ( us_id_pk ) ;
ALTER TABLE USERS ADD CONSTRAINT USERS__us_email UNIQUE ( us_email ) ;
ALTER TABLE USERS ADD CONSTRAINT USERS__us_login UNIQUE ( us_login ) ;
/

ALTER TABLE APARTMENTS ADD CONSTRAINT APARTMENTS_CITIES_FK FOREIGN KEY ( ap_city_id ) REFERENCES CITIES ( ct_id_pk ) ON
DELETE CASCADE ;
/
ALTER TABLE APARTMENTS ADD CONSTRAINT APARTMENTS_USERS_FK FOREIGN KEY ( ap_owner_id ) REFERENCES USERS ( us_id_pk ) ON
DELETE CASCADE ;
/
ALTER TABLE CITIES ADD CONSTRAINT CITIES_COUNTRIES_FK FOREIGN KEY ( ct_country_id ) REFERENCES COUNTRIES ( cn_id_pk ) ON
DELETE CASCADE ;
/
CREATE SEQUENCE apartments_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;
/
create or replace trigger apartments_trg
before insert on APARTMENTS
for each row
begin
  if :new.ap_id_pk is null then
    select apartments_seq.nextval into :new.ap_id_pk from dual;
  end if;
end;
/
CREATE SEQUENCE users_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;
/
create or replace trigger users_trg
before insert on USERS
for each row
begin
  if :new.us_id_pk is null then
    select users_seq.nextval into :new.us_id_pk from dual;
  end if;
end;
/
CREATE SEQUENCE countries_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;
/
create or replace trigger countries_trg
before insert on COUNTRIES
for each row
begin
  if :new.cn_id_pk is null then
    select countries_seq.nextval into :new.cn_id_pk from dual;
  end if;
end;
/
CREATE SEQUENCE cities_seq
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;
/
create or replace trigger cities_trg
before insert on CITIES
for each row
begin
  if :new.ct_id_pk is null then
    select cities_seq.nextval into :new.ct_id_pk from dual;
  end if;
end;